name: Publish Docker Image

on:
    push:
        branches:
            - master
    release:
        types: [created]

env:
    IMAGE_NAME: wesleyklop/wesley.io/site

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: elgohr/Publish-Docker-Github-Action@master
              with:
                  name: ${{ env.IMAGE_NAME }}
                  username: ${{ github.actor }}
                  password: ${{ github.token }}
                  registry: docker.pkg.github.com
                  tag_semver: true
