name: Deliver

on:
  push:
    branches:
      - main
  release:
    types:
      - created

permissions:
  contents: read
  packages: write

concurrency:
  cancel-in-progress: true
  group: ci/${{ github.ref_name || 'shared' }}

env:
  HUSKY: 0

jobs:
  build-push:
    name: Build (and push) Docker image
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        if: github.event_name != 'pull_request'
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - id: meta
        uses: docker/metadata-action@v3.6.2
        with:
          images: ghcr.io/${{ github.repository }}
          flavor: |
            latest=true
          tag-semver: |
            type=edge,branch=main
            {{version}}
            {{major}}.{{minor}}
            {{major}}
      - name: Build and push docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
