name: Publish Docker Image

on:
    push:
        branches:
            - master
            - develop

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Publish Site to Registry
              uses: elgohr/Publish-Docker-Github-Action@master
              with:
                  name: wesleyklop/wesley.io/site
                  username: ${{ github.actor }}
                  password: ${{ github.token }}
                  registry: docker.pkg.github.com
                  dockerfile: Dockerfile
                  tag_semver: true
